### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by aliatiia** [nmohnblatt/zk-jargon-decoder#1]
Link to the PDF in the cited reference is broken (should be `~` instead of space), [this page](https://nmohnblatt.github.io/zk-jargon-decoder/definitions/polynomial_interactive_oracle_proof.html)

[https://www.di.ens.fr/**~**nitulesc/files/Survey-SNARKs.pdf](https://www.di.ens.fr/~nitulesc/files/Survey-SNARKs.pdf)

**Comment by nmohnblatt** [comment]
Thanks for noticing! Seems to be a bug with bibtex and parsing URLs (see here https://github.com/zotero/translators/issues/2313 )

Worked around the issue by linking to a different website
