### ISSUE TITLE
Entry for nullifier is empty

### ISSUE THREAD

**Issue by johnsaigle** [nmohnblatt/zk-jargon-decoder#2]
Hello, thanks for the great resource!

The text for 'Nullifier' is empty.

**Comment by nmohnblatt** [comment]
Glad it helps! Thanks for noticing that, I think it was part of my TODOs but somehow made it onto the main deployment. Hoping to fill in these blank entries soon

**Comment by nmohnblatt** [comment]
@johnsaigle entry is now up! Closing this issue :)
